-- ============================================================
-- ELECTRONICS STORE MANAGEMENT SYSTEM
-- 04_functions.sql — Stored Functions
-- Course: UCS310 – Database Management Systems
-- Group 2Q21 | Thapar Institute of Engineering & Technology
-- ============================================================

DELIMITER $$

-- ============================================================
-- FUNCTION 1: fn_get_product_stock
-- Returns the current stock level for a given product.
-- ============================================================
DROP FUNCTION IF EXISTS fn_get_product_stock$$

CREATE FUNCTION fn_get_product_stock(p_product_id INT)
RETURNS INT
DETERMINISTIC
READS SQL DATA
BEGIN
    DECLARE v_stock INT DEFAULT 0;

    SELECT quantity_in_stock INTO v_stock
    FROM INVENTORY
    WHERE product_id = p_product_id;

    -- If no record found, return 0
    IF v_stock IS NULL THEN
        SET v_stock = 0;
    END IF;

    RETURN v_stock;
END$$


-- ============================================================
-- FUNCTION 2: fn_calculate_order_total
-- Calculates the total amount for a given order by summing
-- the subtotals of all its order items.
-- ============================================================
DROP FUNCTION IF EXISTS fn_calculate_order_total$$

CREATE FUNCTION fn_calculate_order_total(p_order_id INT)
RETURNS DECIMAL(12,2)
DETERMINISTIC
READS SQL DATA
BEGIN
    DECLARE v_total DECIMAL(12,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(quantity * unit_price), 0.00)
    INTO v_total
    FROM ORDER_ITEMS
    WHERE order_id = p_order_id;

    RETURN v_total;
END$$


-- ============================================================
-- FUNCTION 3: fn_get_customer_total_spend
-- Returns the total lifetime spending of a customer
-- across all their orders.
-- ============================================================
DROP FUNCTION IF EXISTS fn_get_customer_total_spend$$

CREATE FUNCTION fn_get_customer_total_spend(p_customer_id INT)
RETURNS DECIMAL(12,2)
DETERMINISTIC
READS SQL DATA
BEGIN
    DECLARE v_total_spend DECIMAL(12,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(total_amount), 0.00)
    INTO v_total_spend
    FROM ORDERS
    WHERE customer_id = p_customer_id
      AND order_status != 'Cancelled';

    RETURN v_total_spend;
END$$


-- ============================================================
-- FUNCTION 4: fn_get_category_revenue
-- Returns the total revenue generated by all products
-- belonging to a given category.
-- ============================================================
DROP FUNCTION IF EXISTS fn_get_category_revenue$$

CREATE FUNCTION fn_get_category_revenue(p_category_id INT)
RETURNS DECIMAL(12,2)
DETERMINISTIC
READS SQL DATA
BEGIN
    DECLARE v_revenue DECIMAL(12,2) DEFAULT 0.00;

    SELECT COALESCE(SUM(oi.quantity * oi.unit_price), 0.00)
    INTO v_revenue
    FROM ORDER_ITEMS oi
    JOIN PRODUCT p ON oi.product_id = p.product_id
    WHERE p.category_id = p_category_id;

    RETURN v_revenue;
END$$

DELIMITER ;

SELECT 'All stored functions created successfully!' AS status;
